from dotenv import load_dotenv
from openai import OpenAI

from models.generic_workflow import GenericWorkflow


load_dotenv()

client = OpenAI()


def build_workflow_generation_prompt(user_request: str) -> str:
    prompt = f"""
You are the DCP AI Workflow Generator.

Your task is to analyze the user's request and return one valid
GenericWorkflow object matching the provided schema.

USER REQUEST:
{user_request}

CRITICAL OUTPUT RULES:

1. The exact USER REQUEST above is authoritative.

2. Never use placeholder values such as:
   - "string"
   - "integer"
   - "boolean"
   - "date"
   - "list"
   - "enum"
   - "unknown"
   - "None"
   - "null"
   - "N/A"

3. Never copy schema example values into the output.

4. The field `user_request` must contain the exact user request.
   Do not replace it with "string".

5. Extract every value explicitly provided by the user.

6. Every explicitly provided value must be placed in the relevant
   WorkflowField.value.

7. Every explicitly provided value must use:
   source = "user_confirmed"

8. Do not create a suggestion for information already provided
   by the user.

9. Missing information must use:
   value = null
   source = "missing"

10. Never use source = "assumed" unless a real concrete value is
    provided.

11. Create only fields relevant to the user's request.

12. Every field must have:
    - field_name
    - value
    - field_type
    - required
    - question
    - source

13. Use only these field types:
    - string
    - integer
    - boolean
    - date
    - list
    - enum

14. Field names must use lowercase snake_case.

15. workflow_type must use lowercase snake_case.

16. If a required field is missing:
    next_action = "collect_information"

17. If all required fields have values:
    next_action = "generate_prompt"

18. Use next_action = "complete" only when the workflow is fully
    completed and no further action is required.

VALUE EXTRACTION EXAMPLES:

Example 1:
User request:
Plan a 5 day trip for 4 people.

Correct fields:
- trip_duration_days:
  value = "5"
  field_type = "integer"
  source = "user_confirmed"

- number_of_people:
  value = "4"
  field_type = "integer"
  source = "user_confirmed"

Incorrect:
- value = "string"
- value = null
- suggestion containing "5" or "4"

Example 2:
User request:
My budget is 50000 rupees.

Correct:
- budget_in_rupees:
  value = "50000"
  field_type = "integer"
  source = "user_confirmed"

Example 3:
User request:
Starting on 2026-12-20.

Correct:
- start_date:
  value = "2026-12-20"
  field_type = "date"
  source = "user_confirmed"

Example 4:
User request:
Convert the text "hello world" to uppercase.

Correct:
- input_string:
  value = "hello world"
  field_type = "string"
  source = "user_confirmed"

The `user_request` field must contain:
{user_request}

SUGGESTION RULES:

1. Suggestions are optional.
2. Only create a suggestion when a concrete recommendation is useful.
3. Never create a suggestion for information already provided.
4. Never use placeholder or empty suggestion values.
5. Never use:
   - null
   - None
   - N/A
   - unknown
   - empty string
6. Missing information must be represented by a WorkflowField,
   not by a suggestion.
7. If no useful recommendation exists, return an empty suggestions list.

FINAL VALIDATION BEFORE RETURNING:

Check that:

1. workflow.user_request equals the exact USER REQUEST.
2. No field value is a placeholder.
3. No field value is the literal string "string" unless the user
   explicitly provided the word "string".
4. Every user-provided value is marked user_confirmed.
5. Missing required values are null with source missing.
6. No user-provided value is duplicated as a suggestion.
7. next_action matches the required-field completion status.
8. Return only the GenericWorkflow object.
"""

    return prompt


def generate_ai_workflow(user_request: str) -> GenericWorkflow:
    prompt = build_workflow_generation_prompt(user_request)

    response = client.responses.parse(
        model="gpt-4.1-mini",
        input=[
            {
                "role": "system",
                "content": (
                    "You generate accurate structured workflows. "
                    "Never use schema placeholders. "
                    "Always preserve the exact user request."
                ),
            },
            {
                "role": "user",
                "content": prompt,
            },
        ],
        text_format=GenericWorkflow,
    )

    workflow = response.output_parsed

    if workflow is None:
        raise ValueError(
            "The AI did not return a valid structured workflow."
        )

    # Enforce the original request in application code.
    workflow.user_request = user_request

    # Remove accidental placeholder values generated by the AI.
    placeholder_values = {
        "string",
        "integer",
        "boolean",
        "date",
        "list",
        "enum",
        "unknown",
        "None",
        "null",
        "N/A",
    }

    for field in workflow.fields:
        if field.value in placeholder_values:
            field.value = None
            field.source = "missing"

    # Ensure the next action is consistent with required fields.
    required_fields_missing = any(
        field.required and field.value is None
        for field in workflow.fields
    )

    if required_fields_missing:
        workflow.next_action = "collect_information"
    else:
        workflow.next_action = "generate_prompt"

    return workflow